DataWorkflowServices/dws

mount-daemon/controllers/clientmount_controller.go

Fix unmount message for failed mount

---

api/v1alpha1/servers_types.go
config/crd/bases/dws.cray.hpe.com_directivebreakdowns.yaml
config/crd/bases/dws.cray.hpe.com_servers.yaml

- Display the createtime and the status.ready values by default to show when a Servers resource becomes ready during Setup

Add Printcolumns for Servers resource

---

mount-daemon/controllers/clientmount_controller.go

- Ensure LVM volume is deactivated in the case the volume is already unmounted
- Refactors + renames verifyLVMDevice to accept an activation or deactivation parameter - configureLVMDevice.

RABSW-945: Client Mount Daemon might strand volume group

---

mount-daemon/controllers/clientmount_controller.go

Add missing error return; debug output in case of missing VG/LV pair

---

controllers/metrics/metrics.go
controllers/workflow_controller.go
go.mod
vendor/modules.txt

Add some basic seed metrics to the operators,  to act as a pattern for others
to follow.

RABSW-1004 Add metrics support to the operators

---

Makefile

Update to envtest 1.24.2, to work on an M1.

---

api/v1alpha1/workflow_webhook.go

Remove the Info logs from the webhook; they're a bit much

---

api/v1alpha1/workflow_webhook.go

Initialize driver status to Pending

---

api/v1alpha1/storage_types.go
config/crd/bases/dws.cray.hpe.com_storages.yaml

Signed-off-by: Blake Devcich <blake.devcich@hpe.com>

Add SerialNumber, FirmwareVersion, and Slot to Storage resource

---

api/v1alpha1/persistentstorageinstance_types.go

Signed-off-by: Anthony Floeder <anthony.floeder@hpe.com>

Convert deleting to destroying within persistent instance #49

---

api/v1alpha1/workflow_types.go
config/crd/bases/dws.cray.hpe.com_workflows.yaml
config/samples/dws_v1alpha1_workflow.yaml

Add omitempty to the hurry flag.

---

mount-daemon/controllers/clientmount_controller.go
mount-daemon/main.go

Remove the mount location after unmounting.

RABSW-1055: rmdir after unmount

---

.github/workflows/main.yml

Build and do tags on "releases/v*" branches

---

README.md

something that is only in the release branch

---

.github/workflows/verify_tag.yml

Rename the workflow that verifies tags.

---

Makefile
config/manager/manager.yaml

Remove the 'vendor' target from the Makefile; we're no longer using the enterprise github.

Remove the DWS controller node selector.

---

utils/updater/status_updater.go
utils/updater/status_updater_test.go

Refactor 'Status Updater' to support latest controller runtime

---

Makefile

'undeploy' make target requires kustomize

---

api/v1alpha1/persistentstorageinstance_types.go
config/crd/bases/dws.cray.hpe.com_persistentstorageinstances.yaml

RABSW-1099: Change PersistentStorageInstance State field to pascal case

---

api/v1alpha1/clientmount_types.go
config/crd/bases/dws.cray.hpe.com_clientmounts.yaml
mount-daemon/controllers/clientmount_controller.go

RABSW-1097: Set owner and group for raw device mounts

---

.github/workflows/main.yml
.github/workflows/rpm_build.yml
.github/workflows/verify_tag.yml
api/v1alpha1/workflow_webhook.go
utils/dwdparse/dwdparse.go
utils/dwdparse/dwdparse_test.go

Refactor dwdparse utility to simplify things, remove dead code, and migrate to more individualized test cases
All this is to support Rule Definitions with Key values that are regular expressions.
Still trying to learn when to stop

Dwdparse support for regex keys

---

config/crd/bases/dws.cray.hpe.com_clientmounts.yaml
config/crd/bases/dws.cray.hpe.com_computes.yaml
config/crd/bases/dws.cray.hpe.com_directivebreakdowns.yaml
config/crd/bases/dws.cray.hpe.com_dwdirectiverules.yaml
config/crd/bases/dws.cray.hpe.com_persistentstorageinstances.yaml
config/crd/bases/dws.cray.hpe.com_servers.yaml
config/crd/bases/dws.cray.hpe.com_storages.yaml
config/crd/bases/dws.cray.hpe.com_systemconfigurations.yaml
config/crd/bases/dws.cray.hpe.com_workflows.yaml
mount-daemon/controllers/clientmount_controller.go

Consider an unmount successful in clientmountd when the VG/LV isn't found.

Github #40: Succeed unmount when VG/LV is missing

---

deploy.sh

This slipped through the previous PR.

Remove hard-coded overlay in deploy.sh

---

Makefile
config/crd/bases/dataworkflowservices.github.io_clientmounts.yaml
config/crd/bases/dataworkflowservices.github.io_computes.yaml
config/crd/bases/dataworkflowservices.github.io_directivebreakdowns.yaml
config/crd/bases/dataworkflowservices.github.io_dwdirectiverules.yaml
config/crd/bases/dataworkflowservices.github.io_persistentstorageinstances.yaml
config/crd/bases/dataworkflowservices.github.io_servers.yaml
config/crd/bases/dataworkflowservices.github.io_storages.yaml
config/crd/bases/dataworkflowservices.github.io_systemconfigurations.yaml
config/crd/bases/dataworkflowservices.github.io_workflows.yaml

The k8s-go community broke a few things.

Upgrade controller-gen to v0.14.0 and setup-envtest to 3/20/24

---

api/v1alpha2/clientmount_webhook.go
api/v1alpha2/computes_webhook.go
api/v1alpha2/directivebreakdown_webhook.go
api/v1alpha2/dwdirectiverule_webhook.go
api/v1alpha2/persistentstorageinstance_webhook.go
api/v1alpha2/servers_webhook.go
api/v1alpha2/storage_webhook.go
api/v1alpha2/systemconfiguration_webhook.go
api/v1alpha2/webhook_suite_test.go
api/v1alpha2/workflow_webhook.go
api/v1alpha2/workflow_webhook_test.go

Minimize the diffs the diffs we have as we go forward.

Incorporate some differences from a more recent kubebuilder version.

---

config/kind/webhook_patch.yaml
hack/make-kustomization.sh

Fix the indentation for the Deployment template.
Change make-kustomization.sh to not create a patch for a DaemonSet--it's all Deployments anyway.

Fix the webhook in KIND

---

api/v1alpha2/owner_labels.go

Change the match labels to match on the owner UID label.

Match owner UID label

---

api/v1alpha2/owner_labels.go
config/manager/kustomization.yaml

Release v0.1.8

---

api/v1alpha3/owner_labels.go

Add a new type of child deletion that deletes child types in parallel.

Add Parallel Child Deletion

---

api/v1alpha4/conversion.go
api/v1alpha5/conversion.go
config/manager/kustomization.yaml

Release v0.1.14
