DataWorkflowServices/dws

- mount-daemon/controllers/clientmount_controller.go
Failure to deactivate will leave behind a `/dev/mapper/` object. Any reuse of the vg/lv names and the activation will fail
```
$ vgchange --activate y default-nnf08-xfs-0-xfs-0-0_vg
device-mapper: create ioctl on default--nnf08--xfs--0--xfs--0--0_vg-default--nnf08--xfs--0--xfs--0--0_lv LVM-XHV5nm5PfYiZ5YIw09KgZCV38uCyMAnEEEpLHsl78Dox2C1oSjYGPZKsPoiFSuSq failed: Device or resource busy
```
Performing the deactivate fixes this issue
> All LVM volumes must deactivate as part of unmount

- api/v1alpha1/storage_types.go
- config/crd/bases/dws.cray.hpe.com_storages.yaml
In the case when a rabbit is missing all of its drives, the Capacity will be 0. Provide 0 in this case as a courtesy for consumers of the Storages Resource.
> RABSW-986 DWS-Storages: Capacity should always be set even when 0

- controllers/workflow_controller.go
This commit improves how the DWS workflow controller handles multiple #DWs
that have registered for the same workflow phases. If any of the driverStatus
elements for the current phase have an error, then one of the errors is reported
in the workflow status. If that error is resolved, then the workflow status shows
any other errors fom other driverStatus elements. Once there are no errors, then
the workflow status no longer shows an error.
Signed-off-by: Matt Richerson <mattr@cray.com>
> RABSW-996: Handle multiple #DW errors properly

- api/v1alpha1/workflow_types.go
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
This commit adds and error field to the entries in thedriverstatus array.
The error field is meant to provide a non-user facing error message when
something goes wrong. This field is not meant to be rolled up into the overall
status of the workflow, and it is not parsed by the WLM. This field is intended
to be used by admins and developers.
Signed-off-by: Matt Richerson <mattr@cray.com>
> RABSW-999: Add error field to driver status

- api/v1alpha1/workflow_types.go
- api/v1alpha1/workflow_webhook.go
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
- controllers/workflow_controller.go
This commit changes the driver status aggregation to allow using the message field
from a driver entry when the driver hasn't indicated an error. This is used to provide
a human readable string for an error that may be recoverable.
Signed-off-by: Matt Richerson <mattr@cray.com>
> RABSW-999: Change driver status aggregation

- config/default/manager_auth_proxy_patch.yaml
> Update kube-rbac-proxy to v0.13.0, to work on an M1.

- api/v1alpha1/workflow_webhook.go
- config/crd/bases/dws.cray.hpe.com_dwdirectiverules.yaml
- utils/dwdparse/dwdparse.go
- utils/dwdparse/dwdparse_test.go
This commit adds a new option for a rule definition, "uniqueWithin". This
option allows rules to specify that a key/value pair needs to be unique across
multiple #DWs. An example is the "name" field in a jobdw directive. Multiple
jobdws should not use the same value for name. However, The same value for name
can be used between a jobdw and a create_persistent. "uniqueBetween" allows for
this by specifying a key. Values will only be checked for uniqueness for rule
definitions using the same "uniqueBetween" key.
Signed-off-by: Matt Richerson <mattr@cray.com>
> RABSW-1007: Check for unique fields

- api/v1alpha1/directivebreakdown_types.go
- api/v1alpha1/persistentstorageinstance_types.go
- config/crd/bases/dws.cray.hpe.com_persistentstorageinstances.yaml
- controllers/clientmount_controller.go
- controllers/workflow_controller.go
- mount-daemon/controllers/clientmount_controller.go
- utils/updater/status_updater.go
- utils/updater/status_updater_test.go
Talking with @matthew-richerson we want to always make the best attempt to update in the `Close()` routine even when an error is present, but never to override the original error with the Update() error.
This change permits that in the updater code and converts the 3 updater users in DWS to that new API.
> Refactor error handling in updater logic

- controllers/workflow_controller_test.go
The workflow_controller_test.go should expect the workflow with an invalid directive to reach state "Completed". No drivers are registered, so there's nothing to wait for.
> RABSW-1011: Expect test workflow status to be "Completed"

- .github/workflows/rpm_build.yml
- clientmount.spec
This commit adds a spec file to package the clientmount daemon. I added a github action that builds the binary and source RPMs and saves them as an artifact.
> Add spec file and build RPMs in github action (#54)

- .github/workflows/main.yml
- Dockerfile
- Makefile
- api/v1alpha1/webhook_suite_test.go
- api/v1alpha1/workflow_types.go
- api/v1alpha1/workflow_webhook.go
- api/v1alpha1/workflow_webhook_test.go
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
- controllers/suite_test.go
- controllers/workflow_controller_test.go
The Slurm WLM has the concept of entering teardown state with the help of a "hurry" flag. This flag indicates that any in-progress data transfers must be terminated, or that any transfers not yet begun must be skipped.
It is left to the DWS driver implementation to determine how, and whether, to implement this flag.
Add constraints to the webhook to allow the hurry flag to be used only with teardown state.
Hook up the webhook in the controller tests. We need the reconciler running with the webhook to test things in teardown state.
Hook up tests in dockerfile so they run during the github workflow action, and enable tests in the workflow.
> Add a hurry flag to the workflow spec.

- utils/updater/status_updater.go
- utils/updater/status_updater_test.go
This commit allows the error value to pass through the status updater if it was set before the defer function.
> RABSW-1016: Return error from status updater

- Makefile
- api/v1alpha1/workflow_types.go
- api/v1alpha1/workflow_webhook.go
- api/v1alpha1/workflow_webhook_test.go
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
- controllers/workflow_controller.go
- controllers/workflow_controller_test.go
As WorkflowState is a string in the Workflow, change WorkflowState to a native string type.
A couple of helper functions, `state.last()`, `state.next()`, `state.after(state)` were written to replace the logic that checks for valid transitions.
> Rework WorkflowState from int to string

- api/v1alpha1/workflow_types.go
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
- config/samples/dws_v1alpha1_workflow.yaml
***BREAKING CHANGE***
[API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#constants) call for constants to use "CamelCase, with an initial uppercase letter"
This also aligns with the Workflow statuses (Pending, Queued, ...)
> Change WorkflowState values to conform to the Kubernetes API Convention

- Makefile
- config/rbac/kustomization.yaml
- config/rbac/kustomizeconfig.yaml
- config/rbac/service_account.yaml
Kubernetes 1.24 enabled [LegacyServiceAccountTokenNoAutoGeneration](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token#legacyserviceaccounttokennoautogeneration). As such, we need to manually create the Secret. Annotations relate the Secret to the ServiceAccount.
> To support Kubernetes >= 1.24, manually create the SA Secret

- api/v1alpha1/directivebreakdown_types.go
- config/crd/bases/dws.cray.hpe.com_directivebreakdowns.yaml
Add a type and constants for the allocation strategies in the directivebreakdown. Clean up some old kubebuilder validation too.
> RABSW-1079: Add constants for allocation strategies

- Makefile
Signed-off-by: Nathan Lee <nathan.lee@hpe.com>
dws-slurm-bb-plugin will also use Kind for integration testing. Adding support for named clusters will help prevent conflicts when dws and dws-slurm-bb-plugin tests are run on the same machine.
> Adding cluster name to kind-push

- api/v1alpha1/systemconfiguration_types.go
- config/crd/bases/dws.cray.hpe.com_systemconfigurations.yaml
> Remove Rabbit enforcement on the StorageNode.Type

- Makefile
- git-version-gen
On the master branch, allow git-version-gen to use the SHA as the value for the .version file, because there are no tags on the master branch for it to use for that purpose.
This allows nnf-deploy to succeed when using this master branch in a KIND environment.
> On the master branch, allow git-version-gen to use the SHA for .version

- Makefile
Let .version be phony so that a git update to the workarea can be reflected in it each time it's needed.
> Let .version be phony, so it's always updated with the workarea.

- config/manager/manager.yaml
Add a label of app=dws on the DWS pod to make it easier to work with the pod without having to look it up.
Examples:
$ kubectl logs -n dws-operator-system -l app=dws -c manager 
$ kubectl get pod -n dws-operator-system -l app=dws -o jsonpath='{.items[].metadata.name}'
> Add an app label on the DWS pod.

- .vscode/launch.json
For those who use vscode, I updated the test target so it references the correct kubebuilder assets directory. This will work for us x86 folks but you ARM folks are on your own.
Also, ginkgo's "failFast" has been replaced by "fail-fast" so I silence that deprecation message
> Update vscode launch target so reference local kubebuilder assets

- api/v1alpha1/workflow_types.go
- api/v1alpha1/workflow_webhook.go
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
Place the kubebuilder validation enum on the WorkflowState type and not the field
> Workflow State kubebuilder validation enum _type_ (not field)

- api/v1alpha1/workflow_types.go
On a newly created workflow the status.State is an empty string, so when the validation webhook runs the oldState.next() will panic since this is an unhandled case. This doesn't actually cause any problems besides noise in the logs, but I'm squashing it anyways.
> Panic when validation webhook is run on newly created workflow

- .github/workflows/main.yml
- .github/workflows/rpm_build.yml
- .github/workflows/verify_tag.yml
Loosen the branch filter for pushes.
Print some event context, for future debugging.
Remove an unused variable from verify_tag.
Rename some jobs to give them unique names, to help with debugging.
> Allow builds on all branches.

- controllers/clientmount_controller.go
When running in kind, the rabbit nodes have a separate clientmount controller in the nnf-sos code that handles fake Rabbit mounts.
> RABSW-1128: Only fake out clientmounts on compute nodes in kind

- controllers/clientmount_controller.go
Filter ClientMount resources by namespaces starting with "compute" rather than excluding ones that start with "rabbit". The node names in the kind environment do not have "rabbit" in them.
> RABSW-1139: Change ClientMount predicate for kind and test environment

- mount-daemon/controllers/clientmount_controller.go
The Status.Update() call won't generate an event, so a requeue is needed to make sure we continue reconciling the ClientMount.
> RABSW-1140: Requeue after initializing status section in clientmountd

- mount-daemon/controllers/clientmount_controller.go
For shared volume groups, "vgchange --lock-start" is called before the volume group is activated. If the activation fails, the volume group needs a corresponding "vgchange --lock-stop" when unmounting. Check whether the volume group is locked and remove the lock if necessary.
> Github-151: Unlock VG when vg fails to activate

- .github/workflows/rpm_build.yml
- Makefile
- clientmount.spec
- mount-daemon/main.go
- mount-daemon/version/version.go
Print a commit hash and version string when clientmountd starts. This uses the same mechanism as nnf-dm.
> Add commit and version string to clientmountd

- mount-daemon/controllers/clientmount_controller.go
- mount-daemon/main.go
Add a 60 second (configurable) timeout to any commands run by clientmountd. The command is killed so that an error can be logged and recorded in the workflow.
> RABSW-1054: Add timeout for commands run by clientmountd

- config/rbac/clientmount_role.yaml
- config/rbac/clientmount_role_binding.yaml
- config/rbac/clientmount_service_account.yaml
- config/rbac/kustomization.yaml
Add a ServiceAccount for clientmountd that only allows read and write access to the ClientMount resource.
> RABSW-1150: Add ServiceAccount for clientmountd

- controllers/suite_test.go
In the kubebuilder book:
https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html It explains that we should be using the "live" k8s client rather than the one from the manager:
"Note that we set up both a “live” k8s client and a separate client from the manager. This is because when making assertions in tests, you generally want to assert against the live state of the API server. If you use the client from the manager (k8sManager.GetClient), you’d end up asserting against the contents of the cache instead, which is slower and can introduce flakiness into your tests."
> Use the live k8s client object in suite_test.go.

- utils/dwdparse/dwdparse_test.go
- utils/updater/status_updater_test.go
When adding a "-ginkgo.foo" arg to the "go test" command in the "make test" target, two tests were failing because they didn't recognize ginkgo args.
Now a ginkgo arg can be added to that make target, like this:
go test $(TESTDIR) -coverprofile cover.out -ginkgo.v
> Let all tests recognize ginkgo args

- .github/workflows/rpm_build.yml
- Makefile
- clientmount.spec
- mount-daemon/main.go
- mount-daemon/version/version.go
Give the compute daemon a version id similar to the one use for the container image, and let the daemon report its version when requested.
> Create clientmountd's version from git-version-gen

- Makefile
- config/crd/bases/dws.cray.hpe.com_clientmounts.yaml
- config/crd/bases/dws.cray.hpe.com_computes.yaml
- config/crd/bases/dws.cray.hpe.com_directivebreakdowns.yaml
- config/crd/bases/dws.cray.hpe.com_dwdirectiverules.yaml
- config/crd/bases/dws.cray.hpe.com_persistentstorageinstances.yaml
- config/crd/bases/dws.cray.hpe.com_servers.yaml
- config/crd/bases/dws.cray.hpe.com_storages.yaml
- config/crd/bases/dws.cray.hpe.com_systemconfigurations.yaml
- config/crd/bases/dws.cray.hpe.com_workflows.yaml
- config/rbac/clientmount_role.yaml
- config/rbac/role.yaml
- config/rbac/webhook_role.yaml
- config/webhook/manifests.yaml
The older controller-tools would put a creationTimestamp in the resources and would give it a "null" value.
Re-run "make manifests" to let the new controller-gen cleanup this stuff.
> Update controller-tools to v0.12.0

- mount-daemon/main.go
The Makefile target build-daemon builds an executable called `clientmountd` and the specfile also installs it to /usr/bin/clientmountd. When doing an install of the daemon, the service file created is called `clientmount.service` rather than `clientmountd.service`.
Changing the name here allows for consistency, which is necessary for nnf-deploy to use the dws Makefile to build the daemon rather than building itself. With the change to using the Makefile, nnf-deploy will then look for a service named `clientmountd` rather than `clientmount`.
> Change mount daemon name to clientmountd

- Makefile
- config/craystack/kustomization.yaml
- config/csm/kustomization.yaml
- config/default/kustomization.yaml
- config/dp0/kustomization.yaml
- config/kind/kustomization.yaml
This is the version that is installed by the current kubebuilder, v3.12.0. There will be a deprecation warning about patchesStrategicMerge, but this can be ignored.  This warning is tracked in kubebuilder issue #3539.
> Update to kustomize v5.1.1

- .gitignore
- Makefile
- config/manager/kustomization.yaml
- hack/make-kustomization.sh
Avoid editing config/manager/kustomization.yaml to set the image tag.  This causes git to consider the workarea to be dirty, so two consecutive deploys from a workarea that has no other changes will result in the second deploy looking for an image with a "-dirty" tag.
Instead, from the makefile we create a throw-away, and untracked, overlay that will be used to set the image tag.
> Dynamically create an overlay for the image tag

- Makefile
- config/prometheus/kustomization.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_client_clusterrole_binding.yaml
- config/rbac/kustomization.yaml
- deploy.sh
Add a label to the ServiceMonitor resource that will be common across all DWS and NNF repos so we easily tell Prometheus which ones it should select.
Copy the namespace value into config/prometheus so that part of config/ can be deployed on its own.
Add a ClusterRoleBinding that can be used by a metrics reader process to debug the metrics endpoing of the controller.  The ClusterRole is already being installed, and the ServiceAccount is already installed.
Introduce a deploy.sh script for the "make deploy" and "make undeploy" targets. This script will do the usuall deploy/undeploy, but will also determine whether or not the ServiceMonitor resource can be applied.
> Requirements for Prometheus

- Makefile
- deploy.sh
If a tool is not found, such as yq in the middle of a pipeline, then we want the script to fail.
Also quiet some shellcheck warnings.
> Harden deploy.sh

- Dockerfile
- Makefile
Add the docker-buildx Makefile target that is created by kubebuilder 3.14.0.
The current kubebuilder adds some cross-platform build support in the
Makefile and Dockerfile. Incorporate those pieces into our build.
> Support multi architecture building

- Makefile
When creating the config/begin overlay for CSM, carry forward the dws newName value from the config/csm overlay kustomization. The CSM overlay exists specifically to provide that newName value, so we don't want to lose it when creating config/begin.
> Handle the config/begin overlay for CSM

- api/v1alpha1/conversion.go
- api/v1alpha1/conversion_test.go
- internal/controller/conversion_test.go
When converting to the v1alpha1 spoke do not add the annotation that is the serialized version of the v1alpha2 hub. On a customer site that annotation is too big for the k8s limit of 262144 bytes.
With this change, we can still convert v1alpha2->v1alpha1 and v1alpha1->v1alph2, but we can't convert v1alpha1->v1alpha2->v1alpha1 and v1alpha2->v1alpha1->v1alpha2. However those last two (1-2-1 and 2-1-2) happen only in the conversion test suite, and that is disabled now.
> Limit the SystemConfiguration CRD conversion

- api/v1alpha1/conversion.go
- api/v1alpha2/clientmount_types.go
- config/crd/bases/dataworkflowservices.github.io_clientmounts.yaml
- controllers/clientmount_controller.go
The current ClientMount columns are not working. The Status.Mounts.Ready fields need to be rolled up into one status to get these to work.
> Fix ClientMount Columns + Add AllReady rollup

- api/v1alpha2/resource_error.go
- config/crd/bases/dataworkflowservices.github.io_clientmounts.yaml
- config/crd/bases/dataworkflowservices.github.io_directivebreakdowns.yaml
- config/crd/bases/dataworkflowservices.github.io_persistentstorageinstances.yaml
- config/crd/bases/dataworkflowservices.github.io_servers.yaml
The ResourceErrorType field was missing the "WLM" type in the kubebuilder validation.
> Fix ResourceError kubebuilder validation

- api/v1alpha2/resource_error.go
- config/crd/bases/dataworkflowservices.github.io_clientmounts.yaml
- config/crd/bases/dataworkflowservices.github.io_directivebreakdowns.yaml
- config/crd/bases/dataworkflowservices.github.io_persistentstorageinstances.yaml
- config/crd/bases/dataworkflowservices.github.io_servers.yaml
- config/manager/kustomization.yaml
> Release v0.1.2

- api/v1alpha2/workflow_types.go
- config/crd/bases/dataworkflowservices.github.io_workflows.yaml
Examples:
```
$ kubectl get workflows
NAME                         STATE   READY   STATUS       JOBID         AGE
fluxjob-201564367429304320   Setup   false   DriverWait   fU8ws95yjjM   15s
fluxjob-201564367362195456   Setup   false   DriverWait   fU8ws8z3nby   15s
$ kubectl get workflows -o wide
NAME                         STATE   READY   STATUS       JOBID         AGE   DESIREDSTATE   DESIREDSTATECHANGE   ELAPSEDTIMELASTSTATE   UID    GID
fluxjob-201564367429304320   Setup   false   DriverWait   fU8ws95yjjM   18s   Setup          13s                  50.577ms               1060   100
fluxjob-201564367362195456   Setup   false   DriverWait   fU8ws8z3nby   18s   Setup          13s                  51.308ms               1060   100
```
Signed-off-by: Blake Devcich <blake.devcich@hpe.com>
> Add UID/GID to workflow `-o wide` output

- github/cluster-api/util/conversion/conversion_test.go
- internal/controller/conversion_test.go
- internal/controller/suite_test.go
This tool uses "marker comments" in the Go code to indicate where generated code should be placed.  These markers are used the same way `controller-gen` uses code markers.
> Add comment markers for the crd-bumper tool

- config/default/kustomization.yaml
- config/default/manager_webhook_patch.yaml
- config/default/webhookcainjection_mutating_patch.yaml
- config/default/webhookcainjection_validating_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager_imagepullsecret_controller_patch.yaml
- config/manager/manager_imagepullsecret_webhook_patch.yaml
Add a stub for manager_webhook_patch.yaml so newer versions of
"kubebuilder create webhook" can be satisfied when they're looking for it.
> Squash the warnings about patchesStrategicMerge

- config/kind/webhook_patch.yaml
- config/manager/kustomization.yaml
- hack/make-kustomization.sh
> Release v0.1.7

- config/manager/manager.yaml
- config/manager/webhook.yaml
Signed-off-by: Blake Devcich <blake.devcich@hpe.com>
> Add localtime mounts

- api/v1alpha3/workflow_webhook.go
- config/webhook/service.yaml
Use a ClusterIP for the dws webhhook.
The LoadBalancer would be used only if things outside the cluster needed to get to the webhook, and we don't have that case.
> Switch dws webhook to a cluster IP
